version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: postgres_luce
    environment:
      POSTGRES_DB: luce-di-villa
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    container_name: redis_luce
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped
    command: redis-server --appendonly yes  # Включаем персистентность

volumes:
  postgres_data:
  redis_data: